### ISSUE TITLE
Help regarding search query

### ISSUE THREAD

**Issue by naveennamani** [Malshare/MalShare-Toolkit#11]
What are the ways one can combine multiple search parameters like if I want to combine YRP/IsPE32 and YRP/inject_thread, how should I combine them for ''and'' and how I can combine the keywords for ''or'' like in YRP/IsPE32 or YRP/IsPE6

**Comment by silascutler** [comment]
So, right now we don't support these types of queries.  However, I'll re-open the issue on the [repo](https://github.com/Malshare/Frontend) for the frontend
